# Generated by Django 4.2.1 on 2023-09-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_image_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='formation',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
