# Generated by Django 4.2.1 on 2023-09-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='profile_image',
            field=models.ImageField(default='blog_but_good\\uploads\\Default_pfp.png', upload_to='uploads'),
        ),
    ]
